namespace BpeChatAI.OpenAI;
/// <summary>Represents the input and output costs per token.</summary>
/// <param name="InputCost">
/// <para>The input cost is the cost of the input tokens.
/// This is the cost of the tokens that were used to
/// generate the completion.</para></param>
/// <param name="OutputCost"><para>The output cost is the
/// cost of the output tokens. This is the cost of the tokens
/// that were generated by the completion.</para></param>
public record struct TokenCosts(decimal InputCost, decimal OutputCost);
